name: Publish 👌

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ./API/API.sln

      - name: Build
        run: dotnet build ./API/API.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./API/API.sln --configuration Release --no-build --output ./publish
