name: Publish 👌

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ./filename.sln

      - name: Build
        run: dotnet build ./filename.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./filename.sln --configuration Release --no-build --output ./publish
