name: Publish 👌

on: 
  workflow_dispatch:
  push:
    branches:
      - deploy

env:
  AZURE_WEBAPP_NAME: MediicareHub
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '7.0.x'
      
      - name: Create .env
        run: |
          touch .env
          echo "API_KEY=${{secrets.API_KEY}}" > .env

      - name: Restore dependencies
        run: dotnet restore ./API/API.sln

      - name: Build
        run: dotnet build ./API/API.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./TestingProject/TestingProject.csproj --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./API/API.sln --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with: 
            app-name: ${{env.AZURE_WEBAPP_NAME}}
            publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
            package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
